### ISSUE TITLE
안녕하세요! 학사일정 관련하여질문하여봅니다.

### ISSUE THREAD

**Issue by rnjsrnrdnjs** [nnnlog/neis#4]
학사일정 test시 console.log(list) 에 {} 빈 객체값이 반환됩니다.

const neis = require("../src/neis");

neis.createSchool(neis.REGION.BUSAN, 'C100000394', neis.TYPE.HIGH).getDiary().then(list => {
	console.log(list)
	for (let day of Object.keys(list)) {
		console.log(day);
		console.log(`${month}/${day}: ${list[day].join(", ")}`);
	}
});

도움좀 주실수있을가요 ㅜㅜㅜ

**Comment by nnnlog** [comment]
수정하였습니다. 감사합니다.

**Comment by rnjsrnrdnjs** [comment]
감사합니다!!!

**Comment by rnjsrnrdnjs** [comment]
감사합니다!!
