### ISSUE TITLE
설날에 죄송합니다... ㅜㅜ 검색기능 관련하여 질문드립니다.

### ISSUE THREAD

**Issue by rnjsrnrdnjs** [nnnlog/neis#5]
어제까지는 

const neis = require("../neis/neis");   //-> 제 폴더 기준 주소 맞게 설정해뒀어요!

neis.searchSchool('동래').then(d => {
	d.forEach(school => {
		console.log("학교 명: " +
			school.name + "\n학교 코드 : " + school.code +
			"\n학교 위치 : " + school.addr + "\n학교 교육청 코드 : " + school.edu +
			"\n학교 유형 : " + neis.TYPE[school.kind] + "\n\n"
		);
	});
});

위 테스트 함수가 잘작동했는데 오늘 함수를 실행하니
```
(node:1296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This e
rror originated either by throwing inside of an async function without a catch bl
ock, or by rejecting a promise which was not handled with .catch(). To terminate
the node process on unhandled promise rejection, use the CLI flag `--unhandled-re
jections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mo
de). (rejection id: 2)
(node:1296) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprec
ated. In the future, promise rejections that are not handled will terminate the N
ode.js process with a non-zero exit code.
```

에러가 발생합니다. 도와주실수있을가요..

**Comment by nnnlog** [comment]
제가 실행했을 때는 오류가 발생하지 않습니다.
`neis.searchSchool(...).then(...).catch(console.log)` 로 바꾸었을 때 콘솔에 나오는 오류를 보여주세요.

**Comment by nnnlog** [comment]
searchSchool에서 특정 지역에 대해 검색하는 경우 발생하는 오류를 찾아 고쳤습니다. 
5b20e73c39cd7a2d3b4fb0a79b91890be6811d64 (neis@0.5.1) 버전으로 업데이트하신 뒤에도 같은 오류가 발생하면 알려주세요.

**Comment by rnjsrnrdnjs** [comment]
감사합니다. 지역정보를 추가하고나서 문제없이 작동합니다!!
